# Generated by Django 2.2 on 2019-04-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_name',
            new_name='created_time',
        ),
    ]
